### ISSUE TITLE
Erreur lors de l'auto_browse

### ISSUE THREAD

**Issue by guicolombel** [metaphysicalfgo/doctolib-chronoslots-scraper#1]
Hello, 

Déjà merci pour ce script !

Juste une petite erreur, quand j'active le `--auto_browse "Brave"`, j'ai l'erreur suivante une idée d'où ça peut venir ?
_PS : Je suis sous Mac et Brave est bien en navigateur par défaut_

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/guillaume/Desktop/doctolib-chronoslots-scraper/main.py", line 185, in <module>
    scrape()
  File "/Users/guillaume/Desktop/doctolib-chronoslots-scraper/main.py", line 169, in scrape
    process_center_availabilities_once(links)
  File "/Users/guillaume/Desktop/doctolib-chronoslots-scraper/main.py", line 146, in process_center_availabilities_once
    drvr = webdriver.Chrome(options = options, executable_path = driver_path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

Merci !

**Comment by metaphysicalfgo** [comment]
Bonjour Guillaume
Il semblerait que l’installation séparée du webdriver Chrome soit nécessaire. Le problème a-t-il été résolu ?
Je mettrai à jour le README en conséquence.

**Comment by guicolombel** [comment]
Bonjour, 
C'est effectivement ça, il fallait le webdriver Chrome :)
Merci pour la réponse !

**Comment by metaphysicalfgo** [comment]
Fixé dans 983e1cf328e2652759fdf3532057459b0b8362fa
