### ISSUE TITLE
openssl error when p_map() is running https_retrieve_center_data()

### ISSUE THREAD

**Issue by Kazquo** [metaphysicalfgo/doctolib-chronoslots-scraper#4]
Well, I have the same problem as related here https://github.com/googleapis/google-cloud-python/issues/3501
It seems httplib2 is codé avec le cul, so we must create a new instance of conn for each thread.

> apr@ap-laptop:~/doctolib-fork$ python3 main.py --city Vitré --limit 1
Retrieving list of proximity centers around Vitré with a limit of 1 pages...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 226.34it/s]

[1] 2021-05-22 01:34:44.305593 : checking 10 centers for available slots...
  0%|                                                                                                                                                                                         | 0/10 [00:01<?, ?it/s]
multiprocess.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/apr/.local/lib/python3.7/site-packages/multiprocess/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/apr/.local/lib/python3.7/site-packages/pathos/helpers/mp_helper.py", line 15, in <lambda>
    func = lambda args: f(*args)
  File "main.py", line 139, in https_retrieve_center_data
    resp = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1352, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 310, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 279, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 197, in <module>
    process_center_availabilities_once(links, iteration)
  File "main.py", line 154, in process_center_availabilities_once
    res = p_map(https_retrieve_center_data, center_data_links)
  File "/home/apr/.local/lib/python3.7/site-packages/p_tqdm/p_tqdm.py", line 60, in p_map
    result = list(generator)
  File "/home/apr/.local/lib/python3.7/site-packages/p_tqdm/p_tqdm.py", line 49, in _parallel
    for item in tqdm(map_func(function, *iterables), total=length, **kwargs):
  File "/home/apr/.local/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/apr/.local/lib/python3.7/site-packages/multiprocess/pool.py", line 748, in next
    raise value
http.client.RemoteDisconnected: Remote end closed connection without response

**Comment by metaphysicalfgo** [comment]
Thanks again for the hint @Kazquo 👍🏻 
This has been fixed in 4bb30f16337199ca0caab84411a1524e267f5359
